---
language: go

sudo: required
dist: trusty

services:
 - docker

go:
 - 1.11

install:
 - GO111module=on go mod vendor
 - GOOS=linux go build -o keysync cmd/keysync/keysync.go
 - GOOS=linux go build -o keyrestore cmd/keyrestore/keyrestore.go
 - GOOS=darwin go build -o keysync cmd/keysync/keysync.go
 - GOOS=darwin go build -o keyrestore cmd/keyrestore/keyrestore.go
 - docker build -t keysync-test -f Dockerfile-test .

script:
 - go test -v .
 - docker run -it keysync-test
