---
language: go

sudo: required
dist: trusty

services:
 - docker

go:
 - 1.9

env:
 - DEP_VERSION="0.5.0"

before_install:
 # Download the binary to bin folder in $GOPATH
 - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
 # Make the binary executable
 - chmod +x $GOPATH/bin/dep

install:
 - dep ensure -vendor-only
 - GOOS=linux go build -o keysync cmd/keysync/keysync.go
 - GOOS=linux go build -o keyrestore cmd/keyrestore/keyrestore.go
 - GOOS=darwin go build -o keysync cmd/keysync/keysync.go
 - GOOS=darwin go build -o keyrestore cmd/keyrestore/keyrestore.go
 - docker build -t keysync-test -f Dockerfile-test .

script:
 - go test -v .
 - docker run -it keysync-test
