---
language: go

sudo: required
dist: trusty

services:
 - docker

go:
 - 1.12.x
 - 1.x

env:
 - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

install:
 - GOOS=linux go build -o keysync cmd/keysync/keysync.go
 - GOOS=linux go build -o keyrestore cmd/keyrestore/keyrestore.go
 - GOOS=linux go build -o keyunwrap cmd/keyunwrap/keyunwrap.go
 - GOOS=darwin go build -o keysync cmd/keysync/keysync.go
 - GOOS=darwin go build -o keyrestore cmd/keyrestore/keyrestore.go
 - GOOS=darwin go build -o keyunwrap cmd/keyunwrap/keyunwrap.go
 - docker build -t keysync-test -f Dockerfile-test .

script:
 - go test -v ./...
 - docker run -it --rm keysync-test
